version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "agenda-petshop"
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - database
    tty: true
    volumes:
      - .:/home/app
      - /home/app/node_modules
